{% set name = "singledispatchmethod" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/singledispatchmethod-{{ version }}.tar.gz
  sha256: 183a7fbeab53b9c9d182f8b8f9c2d7e109a7d40afaa30261d81dd8de68cd73bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools-scm
  run:
    - python >={{ python_min }}

test:
  imports:
    - singledispatchmethod
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ikalnytskyi/singledispatchmethod
  summary: Backport of @functools.singledispatchmethod to Python 2.7-3.7.
  dev_url: https://github.com/ikalnytskyi/singledispatchmethod
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AntoineD
